import { useState } from 'react';
import { ArrowRight, CheckCircle2, Gavel, ShieldCheck } from 'lucide-react';
import { useApp } from '../context';
import { Badge, Btn, Card, SectionHeader } from '../components/ui';
import Nav from '../components/Nav';

export default function BidReview() {
  const { navigate, rfqs, bids, awardBid } = useApp();
  const rfq = rfqs.find(r => r.id === 'CC-RFQ-2041') ?? rfqs[0];
  const available = rfq ? bids.filter(b => b.rfqId === rfq.id) : [];
  const [awarded, setAwarded] = useState<string | null>(available.find(b => b.status === 'awarded')?.id ?? null);
  if (!rfq) return null;
  function award(id: string) { awardBid(id, rfq.id); setAwarded(id); }
  return <div className="min-h-screen bg-[#F4F7F2]"><Nav/><main className="page-shell max-w-screen-xl mx-auto px-6 py-8"><SectionHeader title="Compare supplier bids" sub={`${rfq.title} · ${available.length} response${available.length === 1 ? '' : 's'} · Review evidence before awarding`} action={<Btn variant="outline" onClick={() => navigate('buyer-dashboard')}>← Back to dashboard</Btn>}/><Card className="p-5 mb-6 bg-[#E9F0E8] border-[#9FB7A3]"><div className="flex flex-wrap items-center gap-x-8 gap-y-3 text-sm"><span><strong>Requirement:</strong> {rfq.quantity}</span><span><strong>Delivery:</strong> {rfq.delivery}</span><span><strong>Budget:</strong> {rfq.budget}</span><span className="inline-flex items-center gap-2"><Gavel size={16} className="text-[#2F6B4F]"/><strong>{rfq.status === 'awarded' ? 'Awarded' : 'Open for review'}</strong></span></div></Card>{available.length === 0 ? <Card className="p-12 text-center"><Gavel size={36} className="mx-auto text-[#718276] mb-4"/><h2 className="text-xl font-semibold mb-2">No bids yet</h2><p className="text-sm text-[#607267]">Supplier responses will appear here after they submit a bid.</p></Card> : <div className="grid xl:grid-cols-2 gap-5">{available.map(bid => <Card key={bid.id} className={`p-6 ${awarded === bid.id ? 'border-[#3D7658] ring-2 ring-[#9FB7A3]' : ''}`}><div className="flex items-start justify-between gap-4 mb-5"><div><div className="flex items-center gap-2 mb-2"><Badge variant={awarded === bid.id ? 'green' : 'blue'}>{awarded === bid.id ? 'AWARDED' : 'SUBMITTED'}</Badge><span className="font-mono text-xs text-[#718276]">{bid.id}</span></div><h2 className="text-xl font-semibold">{bid.supplier}</h2><p className="text-sm text-[#607267] mt-1">{bid.listing}</p></div><ShieldCheck size={23} className="text-[#2F6B4F]"/></div><div className="grid grid-cols-2 gap-3 mb-5">{[['Quantity',bid.quantity],['Ex-works',bid.price],['Delivered',bid.delivered],['Lead time',bid.leadTime]].map(([label,value]) => <div key={label} className="rounded-xl border border-[#C7D7C8] p-3"><div className="text-xs text-[#607267]">{label}</div><div className="text-base font-semibold mt-1">{value}</div></div>)}</div><div className="flex items-center gap-2 text-sm text-[#415547] mb-6"><CheckCircle2 size={16} className="text-[#2F6B4F]"/>{bid.evidence} · documentation available for review</div>{awarded === bid.id ? <Btn className="w-full justify-center" onClick={() => navigate('contract')}>Continue to contract <ArrowRight size={15}/></Btn> : <Btn variant="outline" className="w-full justify-center" onClick={() => award(bid.id)}>Award this bid</Btn>}</Card>)}</div>}</main></div>;
}
