import { useApp } from '../context';
import { ArrowRight, Check, CircleHelp, Gavel, PackageCheck, Search, ShieldCheck, Truck } from 'lucide-react';
import { Card, StatCard, Badge, Btn, SectionHeader, Table, ScorePill } from '../components/ui';
import Nav from '../components/Nav';

const reqs = [{ id: 'CC-RFQ-2041', name: 'Q4 2026 Concrete Mineralization', grade: 'Captured CO₂ (≥95%)', vol: '3,200 t', budget: '₹67–80/t', status: 'active', matches: 2 }, { id: 'CC-RFQ-2039', name: 'Food Carbonation — Winter Stock', grade: 'Food Grade (≥99.9%)', vol: '400 t', budget: '₹140–165/t', status: 'active', matches: 0 }];
const orders = [{ id: 'CC-O-9012', supplier: 'Kutch Industrial Materials Pvt. Ltd.', product: 'Food Grade CO₂', qty: '400 t', value: '₹59,200', status: 'in-transit', eta: 'Sep 14' }, { id: 'CC-O-9008', supplier: 'Konkan Refining Services (demo)', product: 'Industrial Grade CO₂', qty: '1,800 t', value: '₹164,700', status: 'quality-check', eta: 'Sep 10' }, { id: 'CC-O-8976', supplier: 'Deccan Metals (demo)', product: 'Captured CO₂', qty: '2,600 t', value: '₹174,200', status: 'delivered', eta: 'Sep 02' }];
const flowData = [{ month: 'Apr', v: 1200 }, { month: 'May', v: 1800 }, { month: 'Jun', v: 1400 }, { month: 'Jul', v: 2200 }, { month: 'Aug', v: 3100 }, { month: 'Sep', v: 2700 }];

export default function BuyerDashboard() {
  const { navigate } = useApp();
  const maxFlow = Math.max(...flowData.map(d => d.v));
  return <div className="min-h-screen bg-[#F4F7F2]"><Nav/><main className="page-shell max-w-screen-xl mx-auto px-6 py-8">
    <SectionHeader title="Buyer Dashboard" sub="Maharashtra Concrete Systems (demo) · Mumbai, Maharashtra" action={<div className="flex flex-wrap gap-3"><Btn variant="outline" onClick={() => navigate('compliance')}>Compliance</Btn><Btn onClick={() => navigate('buyer-requirement')}>+ New requirement</Btn></div>}/>
    <Card className="p-6 mb-7 border-[#9FB7A3]/70 bg-gradient-to-r from-[#E4ECE4] to-[#FFFFFF]"><div className="grid lg:grid-cols-[1.3fr_.7fr] gap-6 items-center"><div><Badge variant="blue">BUYER START HERE</Badge><h1 className="text-2xl font-semibold mt-3 mb-2">Find the right CO₂, compare bids, and secure delivery.</h1><p className="text-base text-[#415547] leading-relaxed max-w-2xl">Start with a requirement. Suppliers respond with specifications, price and delivery terms. Compare the bids, request clarification, choose a quote, then move through contract, payment, logistics and quality acceptance.</p></div><div className="grid grid-cols-2 gap-3">{[['1','Post specs'],['2','Compare bids'],['3','Award quote'],['4','Track delivery']].map(([n,t]) => <div key={n} className="flex items-center gap-3 rounded-lg bg-[#F4F7F2]/70 border border-slate-700/70 p-3"><span className="w-8 h-8 rounded-full bg-[#2F6B4F] text-white flex items-center justify-center font-mono text-sm">{n}</span><span className="text-sm font-medium">{t}</span></div>)}</div></div></Card>
    <div className="grid grid-cols-2 lg:grid-cols-5 gap-4 mb-7"><StatCard label="Active Requirements" value="2" sub="8 supplier matches"/><StatCard label="CO₂ Procured (Sep)" value="2,700 t" trend="+22%" color="green"/><StatCard label="Avg. Delivered Cost" value="₹74/t" trend="-5%" color="green"/><StatCard label="CO₂ Utilized (YTD)" value="18,400 t" sub="in concrete mineralization"/><StatCard label="CO₂ Avoided (YTD)" value="9,200 t" color="green" sub="measured & verified"/></div>
    <div className="grid lg:grid-cols-[1.4fr_.8fr] gap-7 mb-7"><Card className="p-6"><div className="flex items-center justify-between mb-6"><div><h2 className="text-lg font-semibold">CO₂ intake volume</h2><div className="text-sm text-[#607267] font-mono mt-1">Apr – Sep 2026 · tonnes</div></div><Badge variant="green">+22% MoM</Badge></div><div className="flex items-end gap-3 h-48">{flowData.map((d, i) => <div key={i} className="flex-1 flex flex-col items-center gap-2"><div className="text-sm text-[#607267] font-mono">{(d.v / 1000).toFixed(1)}K</div><div className={`w-full rounded-t ${i === flowData.length - 1 ? 'bg-[#2F6B4F]' : 'bg-slate-700'}`} style={{ height: `${Math.max(16, (d.v / maxFlow) * 132)}px` }}/><div className="text-sm text-[#607267]">{d.month}</div></div>)}</div></Card><Card className="p-6"><h2 className="text-lg font-semibold mb-5">How bidding works</h2><div className="space-y-4">{[[Gavel,'1. Suppliers respond','Each bid includes quality, price, volume and delivery terms.'],[Search,'2. Compare apples-to-apples','Use the same requirement to compare bids and request clarification.'],[ShieldCheck,'3. Award with evidence','Select a quote after checking documents, quality and delivery fit.']].map(([Icon,title,body]) => <div key={title as string} className="flex gap-3"><Icon size={19} className="text-[#2F6B4F] mt-0.5 shrink-0"/><div><div className="text-base font-semibold">{title as string}</div><p className="text-sm text-[#607267] mt-1 leading-relaxed">{body as string}</p></div></div>)}</div><Btn className="w-full mt-6" onClick={() => navigate('buyer-requirement')}>Post a requirement <ArrowRight size={15}/></Btn></Card></div>
    <div className="grid lg:grid-cols-[1.45fr_.75fr] gap-7 mb-7"><Card className="overflow-hidden"><div className="px-6 py-5 border-b border-slate-800 flex flex-wrap gap-3 items-center justify-between"><div><h2 className="text-lg font-semibold">Active requirements</h2><p className="text-sm text-[#607267] mt-1">Your live buying opportunities and supplier responses.</p></div><Btn variant="ghost" onClick={() => navigate('buyer-requirement')}>+ Post requirement</Btn></div><Table headers={['Req. ID', 'Name', 'Grade', 'Volume', 'Budget', 'Status', 'Matches']} rows={reqs.map(r => [<span className="font-mono text-[#607267]">{r.id}</span>, r.name, r.grade, <span className="font-mono">{r.vol}</span>, <span className="font-mono">{r.budget}</span>, <Badge variant="green">{r.status.toUpperCase()}</Badge>, <button onClick={() => r.matches > 0 ? navigate('bid-review') : navigate('marketplace')} className="text-sm font-mono text-[#2F6B4F] hover:underline">{r.matches > 0 ? `${r.matches} bids →` : 'Find suppliers →'}</button>])}/></Card><Card className="p-6"><h2 className="text-lg font-semibold mb-5">Buyer readiness</h2><div className="space-y-4"><ScorePill label="Commercial Score" score={79}/><ScorePill label="Climate Score" score={88}/><ScorePill label="Compliance Score" score={82}/><ScorePill label="Payment Reliability" score={96}/></div><div className="mt-5 pt-4 border-t border-slate-800 text-sm text-[#607267]">Complete organization and facility details before awarding a bid.</div></Card></div>
    <Card className="overflow-hidden"><div className="px-6 py-5 border-b border-slate-800 flex flex-wrap gap-3 items-center justify-between"><div><h2 className="text-lg font-semibold">Active & recent orders</h2><p className="text-sm text-[#607267] mt-1">Open an order to track its delivery or quality checkpoint.</p></div><Btn variant="ghost" onClick={() => navigate('logistics')}>Logistics tracker →</Btn></div><Table headers={['Order ID', 'Supplier', 'Product', 'Quantity', 'Value', 'Status', 'ETA']} rows={orders.map(o => [<span className="font-mono text-[#607267]">{o.id}</span>, o.supplier, o.product, <span className="font-mono">{o.qty}</span>, <span className="font-mono font-medium">{o.value}</span>, <Badge variant={o.status === 'in-transit' ? 'blue' : o.status === 'delivered' ? 'green' : 'yellow'}>{o.status.toUpperCase().replace(/-/g, ' ')}</Badge>, o.eta])} onRowClick={i => i === 1 ? navigate('quality-verification') : navigate('logistics')}/></Card>
  </main></div>;
}
