import { ArrowUpRight, BookOpen, CalendarDays, CheckCircle2, Factory, FileText, ExternalLink, Gauge, Leaf, ShieldCheck } from 'lucide-react';
import { useApp } from '../context';
import { Badge, Btn, Card, SectionHeader } from '../components/ui';
import SiteFooter from '../components/SiteFooter';

const timeline = [
  ['28 Jun 2023', 'CCTS notified', 'The Central Government notified the Carbon Credit Trading Scheme under the Energy Conservation Act framework, establishing the Indian Carbon Market structure.'],
  ['Jul 2024', 'Compliance procedure published', 'BEE published the detailed compliance procedure covering targets, monitoring, reporting, verification, issuance, surrender, trading and banking.'],
  ['2025', 'Compliance transition begins', 'India began the gradual transition from the PAT energy-efficiency mechanism toward emissions-intensity targets under CCTS for energy-intensive industry.'],
  ['2025–2026', 'Targets and offset work advance', 'BEE and the Indian Carbon Market portal published target-setting, offset-mechanism, methodology and accredited verification resources. Status and eligibility should be checked against the latest official notice.'],
];

const stories = [
  { icon: Factory, tag: 'Industrial transition', title: 'Cement becomes a practical CCTS readiness case', body: 'Cement is listed among the energy-intensive sectors covered by India’s compliance architecture. For a cement or grinding unit, the useful preparation step is to connect production data, energy use, emissions-intensity calculations, quality evidence and facility identity before a formal reporting cycle.', takeaway: 'What Carbon-Connect can add: facility profiles, source documentation, batch records and evidence links that support—not replace—CCTS reporting.' },
  { icon: Gauge, tag: 'Market infrastructure', title: 'From PAT data discipline to carbon-market data discipline', body: 'BEE describes India’s experience with PAT and other market mechanisms as an important foundation for the ICM. The transition makes clean, comparable operational data increasingly valuable for industrial organizations and their verification partners.', takeaway: 'What Carbon-Connect can add: structured data capture, clear measured/estimated/verified labels and a traceable handoff from source to utilization.' },
  { icon: Leaf, tag: 'Project pathway', title: 'CCUS and removals need a separate instrument check', body: 'The Indian Carbon Market portal describes an offset mechanism for non-obligated entities and includes carbon capture, utilization and storage among listed sector areas. Eligibility, methodology approval, project dates and verification requirements must be checked before making any credit claim.', takeaway: 'What Carbon-Connect can add: a project-readiness checklist and a clear separation between physical CO₂ transactions and CCC eligibility.' },
];

const reading = [
  ['Official', 'BEE Carbon Market overview', 'The primary explanation of India’s compliance and offset mechanisms, institutional roles and carbon credit certificates.', 'https://beeindia.gov.in/show_content.php?lang=1&level=1&ls_id=189&lid=294'],
  ['Official', 'Indian Carbon Market portal — About ICM', 'Official background, sectors, compliance/offset documents, ACVA information and registration pathways.', 'https://indiancarbonmarket.gov.in/about-icm'],
  ['Official', 'BEE CCTS publications and procedures', 'A living list of detailed procedures, target-setting notifications, offset methodologies and methodology consultations.', 'https://beeindia.gov.in/show_content.php?lang=1&level=1&ls_id=136&lid=309'],
  ['Independent tracker', 'ICAP Indian CCTS factsheet', 'Independent implementation tracking of sector coverage, phases, targets, MRV and market design. Use alongside official notices.', 'https://icapcarbonaction.com/en/ets/indian-carbon-credit-trading-scheme'],
  ['Explainer', 'Carbon Market Network — CCTS explained', 'A practical business-oriented explainer of registration, emissions-intensity targets, verification and trading mechanics.', 'https://carbonmarketnetwork.com/blog/indias-carbon-credit-trading-scheme-ccts-explained/'],
];

export default function Insights() {
  const { navigate } = useApp();
  return <div className="min-h-screen bg-[#F4F7F2] text-[#1F2B23]">
    <header className="border-b border-[#C7D7C8] bg-[#F4F7F2]/95 backdrop-blur-xl sticky top-0 z-50"><div className="max-w-screen-xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between gap-4"><button onClick={() => navigate('landing')} className="rounded-lg bg-white px-2 py-1.5 shadow-sm" aria-label="Back to Carbon-Connect home"><img src="/carbon-connect-logo.jpg" alt="CarbonConnect" className="h-9 w-auto max-w-[190px] object-contain" /></button><div className="flex items-center gap-2"><Btn variant="ghost" onClick={() => navigate('resources')}>Trust Center</Btn><Btn onClick={() => navigate('role-selection')}>Get started</Btn></div></div></header>
    <main>
      <section className="max-w-screen-xl mx-auto px-4 sm:px-6 pt-16 pb-14"><div className="grid lg:grid-cols-[1fr_.8fr] gap-12 items-end"><div><Badge variant="blue">INSIGHTS · INDIA CCTS</Badge><h1 className="text-4xl lg:text-5xl font-semibold tracking-[-.04em] leading-tight mt-5 mb-5">What India’s carbon-market buildout means for physical CO₂ workflows.</h1><p className="text-lg text-[#415547] leading-relaxed max-w-2xl">A practical, source-led briefing for suppliers, buyers and industrial teams. CCTS context belongs beside the transaction workflow—not inside unsupported carbon-credit claims.</p><div className="flex flex-wrap gap-3 mt-8"><Btn onClick={() => navigate('resources')}>Open Trust Center <ArrowUpRight size={15}/></Btn><Btn variant="outline" onClick={() => navigate('landing')}>Back to overview</Btn></div></div><Card className="p-6 bg-[#E9F0E8] border-[#9FB7A3]"><div className="flex items-center gap-3 mb-4"><CalendarDays size={20} className="text-[#2F6B4F]"/><span className="text-sm font-semibold">Editorial note · Sep 2026</span></div><p className="text-sm text-[#607267] leading-relaxed">Regulatory implementation changes. This page is an educational product layer, not legal, tax, compliance or verification advice. Always confirm the latest official notice before acting.</p></Card></div></section>

      <section className="border-y border-[#C7D7C8] bg-[#E9F0E8] py-16"><div className="max-w-screen-xl mx-auto px-4 sm:px-6"><SectionHeader title="CCTS initiative timeline" sub="A concise view of the framework Carbon-Connect should help users understand before they transact."/><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{timeline.map(([date, title, body]) => <Card key={title} className="p-5"><div className="font-mono text-sm text-[#2F6B4F] mb-5">{date}</div><h2 className="text-lg font-semibold mb-3">{title}</h2><p className="text-sm text-[#607267] leading-relaxed">{body}</p></Card>)}</div></div></section>

      <section className="max-w-screen-xl mx-auto px-4 sm:px-6 py-16"><div className="max-w-3xl mb-10"><Badge variant="outline">WHY THIS MATTERS FOR CARBON-CONNECT</Badge><h2 className="text-3xl font-semibold tracking-[-.03em] mt-4 mb-4">Turn regulatory context into better operational readiness.</h2><p className="text-base text-[#607267] leading-relaxed">The product opportunity is not to issue or promise CCCs. It is to help industrial teams organize the evidence, identity, measurement and custody data that make a credible transaction and a more prepared reporting workflow.</p></div><div className="grid lg:grid-cols-3 gap-4">{[[ShieldCheck,'Separate instruments','Keep physical CO₂, carbon credits, offsets and CCCs visibly distinct in listings, contracts and dashboards.'],[FileText,'Make evidence portable','Attach certificates, monitoring records, batch references and verification status to the specific product and shipment.'],[CheckCircle2,'Create readiness signals','Show what is complete, estimated, measured, verified or still requires an official review.']].map(([Icon,title,body]) => <Card key={title as string} className="p-6"><Icon size={21} className="text-[#2F6B4F] mb-7"/><h3 className="text-lg font-semibold mb-2">{title as string}</h3><p className="text-sm text-[#607267] leading-relaxed">{body as string}</p></Card>)}</div></section>

      <section className="border-y border-[#C7D7C8] bg-[#E9F0E8] py-16"><div className="max-w-screen-xl mx-auto px-4 sm:px-6"><div className="max-w-3xl mb-8"><Badge variant="outline">REAL STORIES & MARKET SIGNALS</Badge><h2 className="text-3xl font-semibold tracking-[-.03em] mt-4 mb-4">Editorial stories grounded in the transition.</h2><p className="text-base text-[#607267] leading-relaxed">These are practical interpretations of published market developments, not claims that Carbon-Connect or its demo organizations are CCTS participants.</p></div><div className="grid lg:grid-cols-3 gap-4">{stories.map(({icon: Icon, tag, title, body, takeaway}) => <Card key={title} className="p-6 flex flex-col"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-[#2F6B4F] mb-6"><Icon size={17}/>{tag}</div><h3 className="text-xl font-semibold mb-3">{title}</h3><p className="text-sm text-[#607267] leading-relaxed flex-1">{body}</p><div className="mt-6 pt-5 border-t border-[#C7D7C8] text-sm font-medium text-[#415547]">{takeaway}</div></Card>)}</div></div></section>

      <section className="max-w-screen-xl mx-auto px-4 sm:px-6 py-16"><div className="max-w-3xl mb-8"><Badge variant="yellow">ARTICLES & STUDIES</Badge><h2 className="text-3xl font-semibold tracking-[-.03em] mt-4 mb-4">Read the primary sources before making a claim.</h2><p className="text-base text-[#607267] leading-relaxed">Use official Indian sources for obligations and procedures. Use independent trackers and explainers for market interpretation and comparison.</p></div><div className="grid md:grid-cols-2 gap-4">{reading.map(([tag, title, body, url]) => <a key={title} href={url} target="_blank" rel="noreferrer" className="group"><Card className="p-5 h-full interactive-lift"><div className="flex items-center justify-between gap-4 mb-4"><Badge variant={tag === 'Official' ? 'green' : tag === 'Independent tracker' ? 'blue' : 'outline'}>{tag}</Badge><ExternalLink size={16} className="text-[#718276] group-hover:text-[#2F6B4F]"/></div><h3 className="text-lg font-semibold mb-2 group-hover:text-[#2F6B4F]">{title}</h3><p className="text-sm text-[#607267] leading-relaxed">{body}</p></Card></a>)}</div></section>

      <section className="border-t border-[#294133] bg-[#14231B] py-14"><div className="max-w-screen-xl mx-auto px-4 sm:px-6 flex flex-col md:flex-row items-start md:items-center justify-between gap-6"><div><h2 className="text-2xl font-semibold text-white">Need help preparing a structured inquiry?</h2><p className="text-base text-[#D7E4D8] mt-2">Contact the Carbon-Connect team for supplier onboarding, buyer requirements or product questions.</p></div><a href="mailto:pateldhyan011@gmail.com" className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-[#2F6B4F] hover:bg-[#E9F0E8]">Email the team <ArrowUpRight size={16}/></a></div></section>
    </main><SiteFooter />
  </div>;
}
