import { useState, type FormEvent } from 'react';
import { useApp } from '../context';
import type { Role } from '../types';

const demoRoles: { label: string; role: Exclude<Role, null> }[] = [
  { label: 'Seller industry', role: 'seller' },
  { label: 'Buyer industry', role: 'buyer' },
  { label: 'Admin', role: 'admin' },
];

export default function Login() {
  const { navigate, authenticate } = useApp();
  const [selectedRole, setSelectedRole] = useState<Exclude<Role, null>>('buyer');
  const roleLabel = selectedRole === 'seller' ? 'Seller' : selectedRole === 'admin' ? 'Admin' : 'Buyer';
  function handleLogin(event: FormEvent) { event.preventDefault(); authenticate(selectedRole); }
  return <div className="min-h-screen bg-[#F4F7F2] flex"><div className="hidden lg:flex w-1/2 bg-[#2F6B4F] flex-col justify-between p-12"><button onClick={() => navigate('landing')} className="rounded-lg bg-white px-2 py-1.5 shadow-sm" aria-label="Go to CarbonConnect homepage"><img src="/carbon-connect-logo.jpg" alt="CarbonConnect" className="h-10 w-auto max-w-[210px] object-contain" /></button><div><blockquote className="text-2xl font-medium text-white leading-relaxed mb-6">A structured marketplace for Indian industries that capture CO₂ and industries that use it productively.</blockquote><div className="text-[#3F5145] text-xs">Illustrative platform experience · India</div></div><div className="grid grid-cols-2 gap-4">{[['Gujarat','Capture & conditioning'],['Maharashtra','Concrete utilization'],['Rajasthan','Power generation'],['Tamil Nadu','Industrial demand']].map(([v,l])=><div key={v} className="bg-[#FFFFFF]/10 rounded p-3"><div className="text-sm font-semibold text-white">{v}</div><div className="text-xs text-[#3F5145] mt-0.5">{l}</div></div>)}</div></div><div className="flex-1 flex items-center justify-center p-8"><div className="w-full max-w-md"><button onClick={() => navigate('landing')} className="text-xs text-[#718276] hover:text-[#415547] mb-8">← Back to Carbon-Connect</button><h1 className="text-2xl font-semibold text-[#1F2B23] mb-1">Sign in</h1><p className="text-[#607267] text-sm mb-6">Choose a demo workspace, then sign in to continue.</p><div className="grid grid-cols-3 gap-2 mb-6">{demoRoles.map(({ label, role })=><button type="button" key={role} onClick={() => setSelectedRole(role)} className={`py-2.5 text-xs font-medium rounded-lg border transition-colors ${selectedRole===role?'border-[#2F6B4F] bg-[#E4ECE4] text-[#3F5145]':'border-slate-700/70 text-[#607267] hover:border-[#9FB7A3] hover:text-[#314237]'}`}>{label}</button>)}</div><form className="space-y-4" onSubmit={handleLogin}><label className="block text-sm font-medium text-[#415547]">Work email<input required type="email" defaultValue="operations@industry.example" className="mt-1.5 w-full px-3 py-2.5 text-sm border border-slate-600 rounded bg-[#FFFFFF]"/></label><label className="block text-sm font-medium text-[#415547]">Password<input required minLength={6} type="password" defaultValue="demo-password" className="mt-1.5 w-full px-3 py-2.5 text-sm border border-slate-600 rounded bg-[#FFFFFF]"/></label><button type="submit" className="w-full py-2.5 bg-[#2F6B4F] text-white text-sm font-medium rounded-xl hover:bg-[#24553F] transition-colors">Sign in as {roleLabel}</button></form><p className="mt-8 text-xs text-[#718276] text-center">New organization? <button onClick={() => navigate('role-selection')} className="text-[#2F6B4F] font-medium">Apply for access</button></p></div></div></div>;
}
