import { useRef, useState } from 'react';
import Nav from '../components/Nav';
import { Badge, Btn, Card, SectionHeader } from '../components/ui';
import { useApp } from '../context';
import type { OrganizationProfile } from '../types';

const fields: (keyof OrganizationProfile)[] = ['legalName','industry','address','state','city','gstin','cin','representative','email','phone','facilityName','facilityLocation','facilityType','capacity'];
const labels: Record<keyof OrganizationProfile,string> = { legalName:'Legal name', industry:'Industry', address:'Registered address', state:'State', city:'City', gstin:'GSTIN', cin:'CIN / registration information', representative:'Authorized representative', email:'Official email', phone:'Phone', facilityName:'Facility name', facilityLocation:'Facility location', facilityType:'Facility type', capacity:'Operating capacity' };
export default function Profile() {
  const { profile, setProfile, role, documents, addDocument, removeDocument } = useApp();
  const [draft, setDraft] = useState(profile); const [saved, setSaved] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  function save() { setProfile(draft); setSaved(true); setTimeout(() => setSaved(false), 1800); }
  function upload(files: FileList | null) { if (!files) return; Array.from(files).forEach(file => addDocument({ id: `DOC-${Date.now()}-${file.name}`, name: file.name, type: 'Business / compliance document', uploadedAt: new Date().toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' }), status: 'Pending', size: `${(file.size / 1024 / 1024).toFixed(1)} MB` })); }
  return <div className="min-h-screen bg-[#F4F7F2]"><Nav/><main className="max-w-screen-xl mx-auto px-6 py-8"><SectionHeader title="Profile / Organization" sub="Manage organization identity, facility information, verification documents and account settings." action={<Btn onClick={save}>{saved ? 'Saved' : 'Save changes'}</Btn>}/>
    <div className="grid grid-cols-3 gap-6"><div className="col-span-2 space-y-6"><Card className="p-6"><div className="flex items-center justify-between mb-5"><div><h3 className="text-sm font-semibold">Organization information</h3><p className="text-xs text-[#607267] mt-1">Demo values are illustrative and do not represent government approval.</p></div><Badge variant="outline">{role === 'seller' ? 'Seller' : role === 'buyer' ? 'Buyer' : 'Admin'}</Badge></div><div className="grid grid-cols-2 gap-4">{fields.slice(0,10).map(key => <label key={key} className="text-xs text-[#607267]">{labels[key]}<input value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })} className="mt-1 w-full px-3 py-2 text-sm border border-slate-600 rounded bg-[#FFFFFF] text-[#1F2B23]"/></label>)}</div></Card>
      <Card className="p-6"><h3 className="text-sm font-semibold mb-5">Facility information</h3><div className="grid grid-cols-2 gap-4">{fields.slice(10).map(key => <label key={key} className="text-xs text-[#607267]">{labels[key]}<input value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })} className="mt-1 w-full px-3 py-2 text-sm border border-slate-600 rounded bg-[#FFFFFF] text-[#1F2B23]"/></label>)}</div></Card>
      <Card className="p-6"><div className="flex items-center justify-between mb-4"><div><h3 className="text-sm font-semibold">Documents</h3><p className="text-xs text-[#607267] mt-1">Upload evidence for review; upload does not imply Government approval.</p></div><><input ref={inputRef} type="file" multiple className="hidden" onChange={e => upload(e.target.files)}/><Btn variant="outline" onClick={() => inputRef.current?.click()}>Browse files</Btn></></div><div onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); upload(e.dataTransfer.files); }} className="border border-dashed border-slate-600 rounded p-5 text-center text-xs text-[#607267] mb-4 bg-slate-900/50">Drag and drop files here, or browse. Supported: PDF, XLSX, DOCX, PNG.</div><div className="space-y-2">{documents.map(doc => <div key={doc.id} className="flex items-center justify-between border-b border-slate-800 py-3"><div><div className="text-xs font-medium text-[#314237]">{doc.name}</div><div className="text-[11px] text-[#718276]">{doc.type} · {doc.size} · uploaded {doc.uploadedAt}</div></div><div className="flex items-center gap-3"><Badge variant={doc.status === 'Verified' ? 'green' : doc.status === 'Rejected' ? 'red' : 'yellow'}>{doc.status}</Badge><button onClick={() => removeDocument(doc.id)} className="text-xs text-[#718276] hover:text-red-600">Remove</button></div></div>)}</div></Card></div>
      <div className="space-y-6"><Card className="p-5"><h3 className="text-xs font-semibold text-[#607267] uppercase tracking-widest mb-4">Verification status</h3><div className="space-y-3">{['KYB / KYC','Facility verification','Compliance verification'].map((item,i)=><div key={item} className="flex items-center justify-between text-xs"><span>{item}</span><Badge variant={i === 0 ? 'green' : 'yellow'}>{i === 0 ? 'VERIFIED' : 'UNDER REVIEW'}</Badge></div>)}</div></Card><Card className="p-5"><h3 className="text-xs font-semibold text-[#607267] uppercase tracking-widest mb-4">Account settings</h3><div className="space-y-3 text-xs text-[#607267]"><button className="block hover:text-[#2F6B4F]">Password</button><button className="block hover:text-[#2F6B4F]">Notifications</button><button className="block hover:text-[#2F6B4F]">Security</button><button className="block hover:text-[#2F6B4F]">Session management</button></div></Card></div></div>
  </main></div>;
}
