import { ArrowRight, BookOpen, Check, FileCheck2, Factory, HelpCircle, ShieldCheck, Truck } from 'lucide-react';
import { useApp } from '../context';
import { Badge, Btn, Card, SectionHeader } from '../components/ui';
import SiteFooter from '../components/SiteFooter';

const resourceCards = [
  { icon: Factory, title: 'For buyers', body: 'Specify purity, physical state, quantity, location and delivery window before you request a quote.', action: 'Start a buyer requirement', screen: 'role-selection' as const },
  { icon: FileCheck2, title: 'For suppliers', body: 'Prepare a listing with source, quality analysis, facility documentation, available volume and delivery terms.', action: 'Prepare a supplier listing', screen: 'role-selection' as const },
  { icon: ShieldCheck, title: 'Quality & digital passport', body: 'Understand how batch identity, contaminant analysis, custody and delivery acceptance fit together.', action: 'Explore quality evidence', anchor: 'quality' },
  { icon: Truck, title: 'Pricing & logistics', body: 'See how capture, liquefaction, storage, handling, route distance and delivery terms shape a quote.', action: 'Review cost drivers', anchor: 'pricing' },
];

const faqs = [
  ['Is Carbon-Connect a carbon-credit exchange?', 'No. Carbon-Connect is designed for physical CO₂ discovery, specification, quoting, logistics and traceability. Carbon credits, offsets and CCTS certificates are separate instruments and require their own applicable frameworks.'],
  ['What should a buyer specify?', 'A buyer should define intended use, required purity or grade, physical state, quantity, location, delivery window, storage constraints and documentation requirements.'],
  ['What evidence can a supplier provide?', 'A supplier can provide facility identity, source information, certificate of analysis, contaminant results, batch identity, custody records and delivery documentation. Evidence remains subject to applicable verification and regulatory requirements.'],
  ['Does a digital passport prove permanent storage?', 'No. A physical CO₂ passport records batch identity and custody. It is not evidence of permanent storage, a carbon credit, an offset or a government approval unless separately measured and verified under an applicable methodology.'],
];

export default function Resources() {
  const { navigate } = useApp();
  return <div className="min-h-screen bg-[#F4F7F2] text-[#1F2B23]">
    <header className="border-b border-slate-700/70 bg-[#F4F7F2]/95 backdrop-blur-xl sticky top-0 z-50">
      <div className="max-w-screen-xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between gap-4">
        <button onClick={() => navigate('landing')} className="flex items-center gap-2.5" aria-label="Back to Carbon-Connect home"><img src="/carbon-connect-logo.jpg" alt="CarbonConnect" className="h-9 w-auto max-w-[190px] object-contain rounded-md bg-white px-2 py-1.5" /></button>
        <div className="flex items-center gap-2"><Btn variant="ghost" onClick={() => navigate('login')}>Sign in</Btn><Btn onClick={() => navigate('role-selection')}>Get started</Btn></div>
      </div>
    </header>
    <main>
      <section className="max-w-screen-xl mx-auto px-4 sm:px-6 pt-16 pb-14">
        <div className="max-w-3xl"><Badge variant="blue">RESOURCE & TRUST CENTER</Badge><h1 className="text-4xl lg:text-5xl font-semibold tracking-[-.04em] leading-tight mt-5 mb-5">A clearer route from captured CO₂ to productive use.</h1><p className="text-base text-[#415547] leading-relaxed max-w-2xl">Use this guide to understand how Carbon-Connect structures supply, demand, evidence, logistics and compliance context for physical CO₂ transactions in India.</p><div className="flex flex-wrap gap-3 mt-8"><Btn onClick={() => navigate('role-selection')}>Enter the marketplace <ArrowRight size={15}/></Btn><Btn variant="outline" onClick={() => navigate('landing')}>Back to overview</Btn></div></div>
      </section>
      <section className="border-y border-[#C7D7C8] bg-[#E9F0E8] py-14"><div className="max-w-screen-xl mx-auto px-4 sm:px-6"><SectionHeader title="Start with the question you need to answer" sub="Public guidance for buyers, suppliers and teams evaluating traceability."/><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{resourceCards.map(({icon: Icon, title, body, action, screen, anchor}) => <Card key={title} className="p-5 flex flex-col"><div className="w-11 h-11 rounded-xl bg-[#DDE9DE] border border-[#9FB7A3] flex items-center justify-center text-[#2F6B4F] mb-5"><Icon size={20}/></div><h2 className="text-lg font-semibold mb-2">{title}</h2><p className="text-sm text-[#607267] leading-relaxed flex-1">{body}</p><button onClick={() => anchor ? document.getElementById(anchor)?.scrollIntoView({ behavior: 'smooth' }) : navigate(screen!)} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#2F6B4F] hover:text-[#294133] text-left">{action} <ArrowRight size={14}/></button></Card>)}</div></div></section>
      <section id="quality" className="max-w-screen-xl mx-auto px-4 sm:px-6 py-16"><div className="grid lg:grid-cols-[.8fr_1.2fr] gap-10"><div><Badge variant="outline">QUALITY & TRACEABILITY</Badge><h2 className="text-3xl font-semibold tracking-[-.03em] mt-4 mb-4">Make the evidence trail understandable.</h2><p className="text-sm text-[#607267] leading-relaxed">A quality record should help a buyer understand what was measured, when it was measured, which batch it applies to, who handled it and what remains subject to verification.</p></div><div className="grid sm:grid-cols-2 gap-3">{[['01','Batch identity','Unique batch and listing references connect product, documents and shipment.'],['02','Specification','Purity, physical state, temperature, pressure and contaminants describe what is being offered.'],['03','Custody','Handoffs, tank or container references and delivery records preserve the chain of custody.'],['04','Utilization','The receiving organization records acceptance, intended use and measured or estimated outcomes.']].map(([n,t,b]) => <Card key={n} className="p-5"><div className="font-mono text-sm text-[#2F6B4F] mb-4">{n}</div><h3 className="font-semibold mb-2">{t}</h3><p className="text-sm text-[#607267] leading-relaxed">{b}</p></Card>)}</div></div></section>
      <section id="pricing" className="border-y border-slate-700/70 bg-[#E9F0E8] py-16"><div className="max-w-screen-xl mx-auto px-4 sm:px-6"><div className="grid lg:grid-cols-[1fr_1fr] gap-10 items-start"><div><Badge variant="outline">PRICING & LOGISTICS</Badge><h2 className="text-3xl font-semibold tracking-[-.03em] mt-4 mb-4">A quote is more than an ex-works number.</h2><p className="text-sm text-[#607267] leading-relaxed">Delivered cost depends on the molecule and the route. Carbon-Connect separates production, liquefaction, storage, quality control, handling, platform, transport, tolls, discharge and applicable taxes or levies so teams can compare assumptions before commitment.</p></div><Card className="p-6"><h3 className="text-sm font-semibold mb-4">Typical quote inputs</h3><div className="grid sm:grid-cols-2 gap-3">{['CO₂ grade and purity','Annual and minimum volume','Origin and destination','Physical state and storage','Delivery terms and lead time','Analysis and documentation'].map(item => <div key={item} className="flex gap-2 text-sm text-[#415547]"><Check size={15} className="text-[#2F6B4F] shrink-0 mt-0.5"/>{item}</div>)}</div></Card></div></div></section>
      <section className="max-w-screen-xl mx-auto px-4 sm:px-6 py-16"><div className="max-w-3xl"><Badge variant="yellow">INDIA MARKET CONTEXT</Badge><h2 className="text-3xl font-semibold tracking-[-.03em] mt-4 mb-4">A marketplace layer alongside the applicable framework.</h2><p className="text-sm text-[#607267] leading-relaxed">Carbon-Connect does not replace CCTS, BEE, CERC, CPCB or SPCB requirements, PESO requirements where applicable, or food-grade requirements under FSSAI. Teams should assess the permits, safety standards, reporting obligations and verification requirements that apply to their activity before executing a transaction.</p><div className="grid md:grid-cols-3 gap-3 mt-8"><Card className="p-4"><BookOpen size={17} className="text-[#2F6B4F] mb-3"/><h3 className="text-sm font-semibold mb-2">Define the instrument</h3><p className="text-xs text-[#607267] leading-relaxed">Physical CO₂, carbon credits, offsets and certificates are not interchangeable.</p></Card><Card className="p-4"><ShieldCheck size={17} className="text-[#2F6B4F] mb-3"/><h3 className="text-sm font-semibold mb-2">Check the evidence</h3><p className="text-xs text-[#607267] leading-relaxed">Separate measured, estimated and verified values in every reporting workflow.</p></Card><Card className="p-4"><HelpCircle size={17} className="text-[#2F6B4F] mb-3"/><h3 className="text-sm font-semibold mb-2">Review applicability</h3><p className="text-xs text-[#607267] leading-relaxed">Use qualified legal, safety, environmental and food-grade guidance for your facility.</p></Card></div></div></section>
      <section className="border-t border-[#294133] bg-[#14231B] py-16"><div className="max-w-screen-xl mx-auto px-4 sm:px-6"><div className="max-w-2xl mb-8"><Badge variant="outline">FAQ</Badge><h2 className="text-3xl font-semibold tracking-[-.03em] mt-4 text-white">Common questions before a quote.</h2><p className="text-base text-[#D7E4D8] mt-3">Open a question for a concise answer, then use the marketplace to turn the guidance into a structured workflow.</p></div><div className="grid md:grid-cols-2 gap-4">{faqs.map(([q,a]) => <details key={q} className="group rounded-xl border border-[#52715A] bg-[#203A2A] p-5 open:bg-[#294133] transition-colors"><summary className="cursor-pointer list-none flex items-start justify-between gap-4 text-base font-semibold text-white"><span>{q}</span><span className="text-[#B9D0BC] text-xl leading-none group-open:rotate-45 transition-transform">+</span></summary><p className="text-base text-[#D7E4D8] leading-relaxed mt-4 pr-8">{a}</p></details>)}</div></div></section>
    </main>
    <SiteFooter />
  </div>;
}
