import { useApp } from '../context';
import { ArrowRight, Check, FileCheck2, Gavel, PackageOpen, Send, ShieldCheck, Truck } from 'lucide-react';
import { Card, StatCard, Badge, Btn, SectionHeader, Table, ScorePill } from '../components/ui';
import Nav from '../components/Nav';

const listings = [{ id: 'CC-L-4821', grade: 'Food Grade CO₂', purity: '99.92%', vol: '1,200 t', price: '₹148/t', status: 'active', inquiries: 7 }, { id: 'CC-L-4820', grade: 'Industrial Grade CO₂', purity: '99.51%', vol: '8,400 t', price: '₹89/t', status: 'active', inquiries: 14 }, { id: 'CC-L-4815', grade: 'Captured CO₂ (flue gas)', purity: '98.10%', vol: '24,000 t', price: '₹67/t', status: 'active', inquiries: 22 }, { id: 'CC-L-4801', grade: 'Technical Grade CO₂', purity: '98.40%', vol: '6,000 t', price: '₹54/t', status: 'draft', inquiries: 0 }];
const orders = [{ id: 'CC-O-9012', buyer: 'Maharashtra Concrete Systems (demo)', product: 'Food Grade CO₂', qty: '400 t', value: '₹59,200', status: 'in-transit', eta: 'Sep 14' }, { id: 'CC-O-9008', buyer: 'Maharashtra Concrete Systems (demo)', product: 'Captured CO₂', qty: '1,800 t', value: '₹120,600', status: 'delivered', eta: 'Sep 10' }, { id: 'CC-O-8994', buyer: 'Vertis Greenhouse BV', product: 'Industrial Grade CO₂', qty: '2,200 t', value: '₹195,800', status: 'contract', eta: 'Sep 20' }];
const revenueData = [{ month: 'Apr', v: 38 }, { month: 'May', v: 52 }, { month: 'Jun', v: 44 }, { month: 'Jul', v: 61 }, { month: 'Aug', v: 78 }, { month: 'Sep', v: 65 }];

export default function SellerDashboard() {
  const { navigate } = useApp();
  const maxRev = Math.max(...revenueData.map(d => d.v));
  return <div className="min-h-screen bg-[#F4F7F2]"><Nav/><main className="page-shell max-w-screen-xl mx-auto px-6 py-8">
    <SectionHeader title="Seller Dashboard" sub="Kutch Industrial Materials Pvt. Ltd. · Cement Plant Mundra, Gujarat" action={<div className="flex flex-wrap gap-3"><Btn variant="outline" onClick={() => navigate('compliance')}>Compliance</Btn><Btn onClick={() => navigate('create-listing')}>+ New listing</Btn></div>}/>
    <Card className="p-6 mb-7 border-[#9FB7A3]/70 bg-gradient-to-r from-[#E4ECE4] to-[#FFFFFF]"><div className="grid lg:grid-cols-[1.3fr_.7fr] gap-6 items-center"><div><Badge variant="blue">SELLER START HERE</Badge><h1 className="text-2xl font-semibold mt-3 mb-2">Publish a credible listing, win bids, and deliver with confidence.</h1><p className="text-base text-[#415547] leading-relaxed max-w-2xl">Add your source and quality details, set transparent commercial terms, respond to buyer requirements, and keep documents and logistics current. Buyers compare evidence as well as price.</p></div><div className="grid grid-cols-2 gap-3">{[['1','Create listing'],['2','Receive RFQs'],['3','Submit bid'],['4','Deliver & settle']].map(([n,t]) => <div key={n} className="flex items-center gap-3 rounded-lg bg-[#F4F7F2]/70 border border-slate-700/70 p-3"><span className="w-8 h-8 rounded-full bg-[#2F6B4F] text-white flex items-center justify-center font-mono text-sm">{n}</span><span className="text-sm font-medium">{t}</span></div>)}</div></div></Card>
    <div className="grid grid-cols-2 lg:grid-cols-5 gap-4 mb-7"><StatCard label="Active Listings" value="3" sub="1 draft"/><StatCard label="Open Inquiries" value="43" trend="+12" color="green"/><StatCard label="Revenue (Sep)" value="₹375K" trend="+18%" color="green"/><StatCard label="CO₂ Sold (Sep)" value="4,400 t" sub="of 9,600 t available"/><StatCard label="Avg. Delivery SLA" value="98.7%" color="green"/></div>
    <div className="grid lg:grid-cols-[1.4fr_.8fr] gap-7 mb-7"><Card className="p-6"><div className="flex items-center justify-between mb-6"><div><h2 className="text-lg font-semibold">Monthly revenue</h2><div className="text-sm text-[#607267] font-mono mt-1">Apr – Sep 2026 · INR thousands</div></div><Badge variant="green">+18% MoM</Badge></div><div className="flex items-end gap-3 h-48">{revenueData.map((d, i) => <div key={i} className="flex-1 flex flex-col items-center gap-2"><div className="text-sm text-[#607267] font-mono">₹{d.v}K</div><div className={`w-full rounded-t ${i === revenueData.length - 1 ? 'bg-[#2F6B4F]' : 'bg-slate-700'}`} style={{ height: `${Math.max(16, (d.v / maxRev) * 132)}px` }}/><div className="text-sm text-[#607267]">{d.month}</div></div>)}</div></Card><Card className="p-6"><h2 className="text-lg font-semibold mb-5">How supplier bidding works</h2><div className="space-y-4">{[[FileCheck2,'1. Complete evidence','Quality analysis, source, facility and delivery documents create buyer confidence.'],[Gavel,'2. Respond to RFQs','Review buyer specifications and submit an itemized quote with lead time.'],[Send,'3. Manage the award','Clarify terms, sign the contract, dispatch, and keep the buyer updated.']].map(([Icon,title,body]) => <div key={title as string} className="flex gap-3"><Icon size={19} className="text-[#2F6B4F] mt-0.5 shrink-0"/><div><div className="text-base font-semibold">{title as string}</div><p className="text-sm text-[#607267] mt-1 leading-relaxed">{body as string}</p></div></div>)}</div><Btn className="w-full mt-6" onClick={() => navigate('create-listing')}>Create a listing <ArrowRight size={15}/></Btn></Card></div>
    <div className="grid lg:grid-cols-[1.45fr_.75fr] gap-7 mb-7"><Card className="overflow-hidden"><div className="px-6 py-5 border-b border-slate-800 flex flex-wrap gap-3 items-center justify-between"><div><h2 className="text-lg font-semibold">Active CO₂ listings</h2><p className="text-sm text-[#607267] mt-1">Buyers see your specification, evidence, price and availability.</p></div><Btn variant="ghost" onClick={() => navigate('create-listing')}>+ Add listing</Btn></div><Table headers={['Listing ID', 'Grade', 'Purity', 'Volume', 'Price', 'Status', 'Inquiries']} rows={listings.map(l => [<span className="font-mono text-[#607267]">{l.id}</span>, l.grade, <span className="font-mono">{l.purity}</span>, l.vol, <span className="font-mono font-medium text-[#1F2B23]">{l.price}</span>, <Badge variant={l.status === 'active' ? 'green' : 'default'}>{l.status.toUpperCase()}</Badge>, <span className="font-mono">{l.inquiries}</span>])} onRowClick={() => navigate('product-detail')}/></Card><Card className="p-6"><h2 className="text-lg font-semibold mb-5">Seller readiness</h2><div className="space-y-4"><ScorePill label="Commercial Score" score={82}/><ScorePill label="Climate Score" score={74}/><ScorePill label="Compliance Score" score={76}/><ScorePill label="Delivery Reliability" score={98}/></div><div className="mt-5 pt-4 border-t border-slate-800 text-sm text-[#607267]">Keep listing documents current to improve buyer conversion.</div></Card></div>
    <Card className="overflow-hidden mb-7"><div className="px-6 py-5 border-b border-[#C7D7C8] flex flex-wrap gap-3 items-center justify-between"><div><h2 className="text-lg font-semibold">Open buyer RFQs</h2><p className="text-sm text-[#607267] mt-1">Respond with a comparable price, lead time and evidence package.</p></div><Badge variant="blue">1 OPEN</Badge></div><div className="p-5 grid md:grid-cols-[1fr_auto_auto] gap-4 items-center"><div><div className="text-base font-semibold">Q4 2026 Concrete Mineralization</div><div className="text-sm text-[#607267] mt-1">3,200 t · Captured CO₂ ≥95% · Mumbai · Budget ₹67–80/t delivered</div></div><Badge variant="yellow">2 BIDS</Badge><Btn onClick={() => navigate('bid-response')}>Respond to RFQ →</Btn></div></Card><Card className="overflow-hidden"><div className="px-6 py-5 border-b border-slate-800 flex flex-wrap gap-3 items-center justify-between"><div><h2 className="text-lg font-semibold">Recent orders</h2><p className="text-sm text-[#607267] mt-1">Monitor awards, dispatch and settlement progress.</p></div><Btn variant="ghost" onClick={() => navigate('logistics')}>View logistics →</Btn></div><Table headers={['Order ID', 'Buyer', 'Product', 'Quantity', 'Value', 'Status', 'ETA']} rows={orders.map(o => [<span className="font-mono text-[#607267]">{o.id}</span>, o.buyer, o.product, <span className="font-mono">{o.qty}</span>, <span className="font-mono font-medium">{o.value}</span>, <Badge variant={o.status === 'in-transit' ? 'blue' : o.status === 'delivered' ? 'green' : 'yellow'}>{o.status.toUpperCase().replace('-', ' ')}</Badge>, o.eta])} onRowClick={() => navigate('logistics')}/></Card>
  </main></div>;
}
