import { Check } from 'lucide-react';
import type { ReactNode } from 'react';

export function downloadFile(filename: string, content: string, type = 'text/plain') {
  const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url);
}

export function Badge({ children, variant = 'default', className = '' }: { children: ReactNode; variant?: 'default' | 'green' | 'yellow' | 'red' | 'blue' | 'outline'; className?: string }) {
  const styles: Record<string, string> = { default:'bg-[#EEF4ED] text-[#415547] border-[#C7D7C8]', green:'bg-[#E0EDE1] text-[#2F6B4F] border-[#9FB7A3]', yellow:'bg-[#F0EFE2] text-[#6C704D] border-[#C9C79D]', red:'bg-[#F5E7E4] text-[#8A4B43] border-[#D8AAA2]', blue:'bg-[#E5EEF1] text-[#355E68] border-[#A9C5CB]', outline:'bg-transparent text-[#415547] border-[#9FB7A3]' };
  return <span className={`inline-flex items-center px-2 py-1 rounded-md text-[10px] font-medium border tracking-wide transition-colors ${styles[variant]} ${className}`}>{children}</span>;
}

export function Card({ children, className = '', onClick }: { children: ReactNode; className?: string; onClick?: () => void }) {
  return <div onClick={onClick} className={`card-depth bg-[#FFFFFF]/95 border border-slate-700/70 rounded-xl ${onClick ? 'cursor-pointer interactive-lift' : ''} ${className}`}>{children}</div>;
}

export function StatCard({ label, value, sub, trend, color = 'zinc' }: { label: string; value: string; sub?: string; trend?: string; color?: string }) {
  const colors: Record<string, string> = { green:'text-[#2F6B4F]', red:'text-red-300', zinc:'text-[#1F2B23]' };
  return <Card className="p-5"><div className="text-xs text-[#607267] mb-2">{label}</div><div className={`text-2xl font-semibold font-mono ${colors[color] || colors.zinc}`}>{value}</div>{sub && <div className="text-xs text-[#718276] mt-1">{sub}</div>}{trend && <div className={`text-xs mt-1 font-medium ${trend.startsWith('+') ? 'text-[#2F6B4F]' : 'text-red-300'}`}>{trend} vs last month</div>}</Card>;
}

export function Btn({ children, variant = 'primary', onClick, className = '', type = 'button', disabled = false }: { children: ReactNode; variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger'; onClick?: () => void; className?: string; type?: 'button' | 'submit'; disabled?: boolean }) {
  const styles: Record<string, string> = { primary:'bg-[#3D7658] text-white hover:bg-[#2F6B4F] border-transparent shadow-[0_8px_18px_rgba(47,107,79,.2)]', secondary:'bg-[#14231B] text-white hover:bg-[#294133] border-transparent', outline:'bg-[#FFFFFF] text-[#314237] border-[#9FB7A3] hover:border-[#3D7658] hover:bg-[#EAF1E9]', ghost:'bg-transparent text-[#415547] border-transparent hover:bg-[#E4ECE4] hover:text-[#2F6B4F]', danger:'bg-[#9A5147] text-white hover:bg-[#7F4039] border-transparent' };
  return <button type={type} onClick={onClick} disabled={disabled} className={`inline-flex min-h-11 items-center justify-center gap-2 px-4 py-2.5 text-sm font-semibold rounded-xl border disabled:opacity-50 disabled:cursor-not-allowed ${styles[variant]} ${className}`}>{children}</button>;
}

export function SectionHeader({ title, sub, action }: { title: string; sub?: string; action?: ReactNode }) { return <div className="section-header-responsive flex items-start justify-between gap-5 mb-7"><div><h2 className="text-lg font-semibold tracking-[-.015em] text-[#1F2B23]">{title}</h2>{sub && <p className="text-sm text-[#607267] mt-1 leading-relaxed">{sub}</p>}</div>{action && <div className="shrink-0">{action}</div>}</div>; }

export function Table({ headers, rows, onRowClick }: { headers: string[]; rows: (string | ReactNode)[][]; onRowClick?: (i: number) => void }) { return <div className="overflow-x-auto rounded-lg border border-slate-800/80"><table className="w-full text-sm"><thead><tr className="border-b border-slate-700/70 bg-slate-950/20">{headers.map((h,i)=><th key={i} className="text-left text-xs font-medium text-[#607267] py-3 px-3 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{rows.length===0?<tr><td colSpan={headers.length} className="py-10 text-center text-xs text-[#718276]">No records to display.</td></tr>:rows.map((row,i)=><tr key={i} className={`border-b border-slate-800 last:border-0 transition-colors duration-150 ${onRowClick?'cursor-pointer hover:bg-sky-950/20':''}`} onClick={()=>onRowClick?.(i)}>{row.map((cell,j)=><td key={j} className="py-3 px-3 text-[#415547] text-xs">{cell}</td>)}</tr>)}</tbody></table></div>; }

export function ProgressBar({ value, max = 100, color = 'green' }: { value: number; max?: number; color?: string }) { const pct=Math.min(100,(value/max)*100); const colors:Record<string,string>={green:'bg-[#3D7658]',amber:'bg-[#9A9A62]',red:'bg-[#B35C52]',blue:'bg-[#527F86]',zinc:'bg-[#819488]'}; return <div className="w-full h-2 bg-[#E0EAE0] rounded-full overflow-hidden"><div className={`h-full rounded-full transition-all duration-500 ${colors[color]||colors.green}`} style={{width:`${pct}%`}}/></div>; }
export function ScorePill({ label, score, max = 100 }: { label: string; score: number; max?: number }) { const pct=(score/max)*100; const color=pct>=80?'text-[#2F6B4F]':pct>=60?'text-amber-200':'text-red-300'; return <div className="flex flex-col gap-1"><div className="flex items-center justify-between"><span className="text-xs text-[#607267]">{label}</span><span className={`text-xs font-semibold font-mono ${color}`}>{score}</span></div><ProgressBar value={score} max={max} color={pct>=80?'green':pct>=60?'amber':'red'}/></div>; }
export function FormRow({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <div className="grid grid-cols-3 gap-4 items-start py-4 border-b border-slate-800 last:border-0"><div><label className="text-sm font-medium text-[#415547]">{label}</label>{hint&&<p className="text-xs text-[#718276] mt-0.5">{hint}</p>}</div><div className="col-span-2">{children}</div></div>; }
export function Input({ placeholder, value, type='text', className='', onChange }: { placeholder?: string; value?: string; type?: string; className?: string; onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void }) { return <input type={type} {...(onChange ? { value, onChange } : { defaultValue: value })} placeholder={placeholder} className={`w-full px-3 py-2 text-sm border border-slate-600 rounded-md bg-[#FFFFFF] text-[#1F2B23] placeholder-[#819488] focus:outline-none focus:border-[#2F6B4F] focus:ring-2 focus:ring-[#2F6B4F]/20 transition-colors ${className}`}/>; }
export function Select({ options, value, onChange }: { options:string[]; value?:string; onChange?: (e: React.ChangeEvent<HTMLSelectElement>) => void }) { return <select {...(onChange ? { value, onChange } : { defaultValue: value })} className="w-full px-3 py-2 text-sm border border-slate-600 rounded-md bg-[#FFFFFF] text-[#1F2B23] focus:outline-none focus:border-[#2F6B4F] focus:ring-2 focus:ring-[#2F6B4F]/20 transition-colors appearance-none">{options.map(o=><option key={o}>{o}</option>)}</select>; }
export function Chip({ label, active=false, onClick }: { label:string; active?:boolean; onClick?:()=>void }) { return <button onClick={onClick} className={`px-3 py-2 text-sm font-medium rounded-lg border transition-colors duration-150 ${active?'bg-[#3D7658] text-white border-[#3D7658] shadow-[0_6px_16px_rgba(47,107,79,.18)]':'bg-[#FFFFFF] text-[#415547] border-[#C7D7C8] hover:border-[#3D7658] hover:text-[#2F6B4F]'}`}>{label}</button>; }
export function StatusDot({ status }: { status:'active'|'pending'|'inactive'|'error' }) { const colors={active:'bg-[#3D7658]',pending:'bg-amber-400',inactive:'bg-slate-500',error:'bg-red-500'}; return <span className={`inline-block w-2 h-2 rounded-full ${colors[status]}`} aria-label={status}/>; }
export function FlowStep({ number,title,desc,active=false,done=false }: { number:number; title:string; desc?:string; active?:boolean; done?:boolean }) { return <div className={`flex gap-4 ${!active&&!done?'opacity-50':''}`}><div className="flex flex-col items-center"><div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-semibold border-2 ${done?'bg-[#2F6B4F] border-[#2F6B4F] text-white':active?'bg-[#FFFFFF] border-[#2F6B4F] text-[#2F6B4F]':'bg-[#FFFFFF] border-slate-600 text-[#718276]'}`}>{done?<Check size={14} strokeWidth={2.5}/>:number}</div><div className="w-px flex-1 bg-slate-700 mt-1"/></div><div className="pb-6"><div className={`text-sm font-medium ${active?'text-[#1F2B23]':done?'text-[#415547]':'text-[#718276]'}`}>{title}</div>{desc&&<div className="text-xs text-[#718276] mt-0.5">{desc}</div>}</div></div>; }
